# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: H1S97X
favicon: '/favicon.ico?v=20240507'
avatar: '/images/calf.png'
subtitle: '技术分享与生活记录 | 或有月下赏花人 应无所憾'
description: '专注于技术开发、系统运维、游戏世界和学术学习的个人博客'
keywords: '技术博客,编程,开发,运维,游戏,学习'
author: H1S97X
language:
  - zh-CN
  - en
timezone: 'Asia/Shanghai'
# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://h1s97x.github.io
permalink: blog/:year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Will be processed by `./scripts/generators/duplicates.js`.
# Usage similar to https://github.com/hexojs/hexo-generator-alias
# new route: source route
# duplicates:
#   /index.html: /notes/index.html

# Directory
source_dir: source
public_dir: public
tag_dir: blog/tags
archive_dir: blog/archives
category_dir: blog/categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# TODO
# 如果要把 posts 目录调整成 `slug/index.md` 形式，要修改：
#   new_post_name: :year/:title/index.md
#   Makefile 里 post 命令的 -p 参数相应调整
# 问题是 assets 只能放到 `slug/index/` 目录下，否则无法被拷贝到 public 目录。

# Writing
new_post_name: blog/:year/:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true # https://hexo.io/docs/asset-folders#Post-Asset-Folder
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

marked: # https://github.com/hexojs/hexo-renderer-marked
  prependRoot: true
  postAsset: true

markdown: # https://github.com/hexojs/hexo-renderer-markdown-it
  preset: 'default'
  anchors:
    permalink: true
    permalinkClass: 'headerlink'
    permalinkSymbol: ''
    separator: ' '
  plugins:
    - name: 'markdown-it-attrs'
    - name: markdown-it-container
      options: invert-when-dark
    - name: markdown-it-container
      options: invert-when-light
    - name: '@traptitech/markdown-it-katex'
      options: # see https://katex.org/docs/options.html
        skipDelimitersCheck: true
    # Don't use `markdown-it-obsidian-imgsize`,
    # which will break `markdown-it-attrs`'s functionality of setting attrs to images.

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 8
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'date'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 8
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
# Hidden files and files/folders with a name that starts with an underscore, are ignored by default.
include: []
exclude:
  - consistency-report.md
ignore: []

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: stellar
aplayer:
  meting: true
  asset_inject: false
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# RSS Feed
## Docs: https://github.com/hexojs/hexo-generator-feed
feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content: true
  content_limit: 300
  content_limit_delim: ' '
  order_by: -date
  icon: favicon.ico
  autodiscovery: true

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:h1s97x/H1S97X.github.io.git
  branch: gh-pages
