######## Sidebar ########
# 左上角显示的 logo 区域，包含图标、大标题、副标题
logo:
  avatar: '[{config.avatar}](/about/)'
  title: '[{config.title}](/)' 
  subtitle: '{config.subtitle}'

menubar:
  columns: 4
  items:
    - id: post
      theme: '#1BCDFC'
      icon: solar:documents-bold-duotone
      title: 博客
      url: /blog/
    - id: notes
      theme: '#1BCDFC'
      icon: solar:notebook-bold-duotone
      title: 笔记
      url: /notes/
    - id: coding
      theme: '#3DC550'
      icon: solar:sidebar-code-bold-duotone
      title: Coding
      url: /coding/
    - id: about
      theme: '#F44336'
      icon: solar:user-bold-duotone
      title: 关于
      url: /about/


inject:
  head:
    - <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png?v=20240514">
    - <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png?v=20240507">
    - <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png?v=20240507">
    - <link rel="manifest" href="/favicon/site.webmanifest?v=20240507">
    - <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@callmebill/lxgw-wenkai-web@1.511.0/style.css">
    - <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/source-code-pro@2.38.0/source-code-pro.min.css">
    # - <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/prismjs@1.30.0/themes/prism.min.css">
    - <link rel="stylesheet" href="/css/gocalf.css?v=20251229">
    - <link rel="stylesheet" href="/css/alert.css?v=20251225">
  # script:
  #   <script src="https://cdn.jsdelivr.net/npm/prismjs@1.30.0/plugins/autoloader/prism-autoloader.min.js"></script>

######## Main ########
site_tree:
  post:
    leftbar: welcome, related, recent
  index_wiki:
    leftbar: welcome, related, recent
  wiki:
    leftbar: welcome, tree, related, recent
  notebooks:
    leftbar: welcome, recent
  notes:
    leftbar: welcome, tagtree, recent_long
  note:
    leftbar: welcome, tagtree, recent_long
  error_page:
    leftbar: welcome, recent, timeline
  page:
    leftbar: welcome, recent

######## Notebook ########
notebook:
  tagcons:
    calf: calf:gocalf
    difficult: hugeicons-pro:dead
    easy: iconoir:one-star
    font: solar:text-linear
    game: solar:gamepad-linear
    git: brand:git
    hard: iconoir:three-stars
    it: solar:code-linear
    mac: brand:apple
    math: solar:calculator-minimalistic-linear
    medium: iconoir:two-stars
    puzzle: hugeicons-pro:puzzle
    python: brand:python

######## Article ########
article:
  license: '本文由 [Calf](/) 原创，采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。'
  share: [link, wechat, email]

######## Comments ########
comments:
  service: giscus
  giscus:
    data-repo: calfzhou/gocalf.com

######## Footer ########
footer:
  social:
    email:
      icon: brand:gmail
      url: mailto:calf.zhou@gmail.com
    github:
      icon: brand:github
      url: https://github.com/calfzhou
    facebook:
      icon: brand:facebook
      url: https://www.facebook.com/calfzhou
    telegram:
      icon: brand:telegram
      url: https://t.me/calfzhou
    pgp:
      icon: other:fingerprint-duotone
      url: /pgp/
    theme:
      icon: default:theme
      onclick: 'switchTheme()'
  sitemap:
    - title: GoCalf
      items:
        - '[主页](/)'
        - '[关于](/about/)'
        - '[PGP 信息](/pgp/)'
        - '[旧站](https://blog.gocalf.com/)'
    - title: 内容
      items:
        - '[笔记<span class="dot"></span>杂七杂八](/notes/)'
        - '[笔记<span class="dot"></span>Coding](/coding/)'
        - '[博客<span class="dot"></span>近期发布](/)'
        - '[博客<span class="dot"></span>归档](/blog/archives/)'
        - '[所有 Wiki 项目](/wiki/)'
        - '[所有笔记本](/notebooks/)'
    - title: 联系我
      items:
        - '[给我发邮件](mailto:calf.zhou@gmail.com)'
        - '[GitHub](https://github.com/calfzhou)'
        - '[Facebook](https://www.facebook.com/calfzhou)'
        - '[Telegram](https://t.me/calfzhou)'
    - title: 特别感谢
      items:
        - '[Hexo](https://hexo.io/)'
        - '[Hexo Stellar](https://xaoxuu.com/wiki/stellar/)'
        - '[霞鹜文楷](https://github.com/lxgw/LxgwWenKai)'
        - '[今日诗词](https://www.jinrishici.com/)'
  content: |
    本站所有文章除特别声明外，均采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。
    本站由 [Hexo](https://hexo.io/)、[{theme.name} {theme.version}]({theme.tree}) 和 [GitHub Pages](https://pages.github.com/) 强力驱动。
    Copyright © 2011-2024 [gocalf.com](/) 保留所有权利。

data_services:
  contributors:
    edit_this_page: # 从开头开始匹配替换
      '': https://github.com/calfzhou/gocalf.com/blob/main/source/

plugins:
  katex:
    # markdown-it-katex 会完成 Katex 渲染，但需要通过 `enable: true` 来注入 Katex CSS
    enable: false # 仅在需要的页面内通过 front-matter 启用
    # Stellar 1.33.1 默认的 Katex 配置，会在正常的公式下边多显示一样格式错误的公式，故改为如下配置
    # See: https://github.com/xaoxuu/hexo-theme-stellar/issues/621#issuecomment-3390421599
    inject: |
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.23/dist/katex.min.css" integrity="sha384-//SZkxyB7axjCAopkAL1E1rve+ZSPKapD89Lo/lLhcsXR+zOYl5z6zJZEFXil+q0" crossorigin="anonymous">
  mermaid:
    enable: false # 仅在需要的页面内通过 front-matter 启用
    js: https://cdn.jsdelivr.net/npm/mermaid@11.8.1/dist/mermaid.min.js
  animcube2:
    enable: false
    inject: |
      <script src="/js/plugins/AnimCube2.min.js?v=20251227"></script>
  animcube3:
    enable: false
    inject: |
      <script src="/js/plugins/AnimCube3.min.js?v=20251227"></script>
  animcube4:
    enable: false
    inject: |
      <script src="/js/plugins/AnimCube4.min.js?v=20251227"></script>
  animcube5:
    enable: false
    inject: |
      <script src="/js/plugins/AnimCube5.min.js?v=20251227"></script>
  animcube6:
    enable: false
    inject: |
      <script src="/js/plugins/AnimCube6.min.js?v=20251227"></script>
  animcube7:
    enable: false
    inject: |
      <script src="/js/plugins/AnimCube7.min.js?v=20251227"></script>

style:
  prefers_theme: dark # auto / light / dark
  font-size:
    root: 18px
  font-family:
    logo: '"LXGW WenKai", "Helvetica Neue", Helvetica, "Lucida Grande", Lucida, Tahoma, Arial, "Microsoft YaHei", "PingFang SC", "Hiragino Sans GB", "Heiti SC", "WenQuanYi Micro Hei", STXiHei, SimHei, sans-serif'
    body: '"LXGW WenKai", "Helvetica Neue", Helvetica, "Lucida Grande", Lucida, Tahoma, Arial, "Microsoft YaHei", "PingFang SC", "Hiragino Sans GB", "Heiti SC", "WenQuanYi Micro Hei", STXiHei, SimHei, sans-serif'
    code: '"LXGW WenKai", "Source Code Pro", Monaco, Menlo, Consolas, "Courier New", monospace'
    codeblock: '"Source Code Pro", Monaco, Menlo, Consolas, "Courier New", monospace, "LXGW WenKai Mono"'
  border-radius:
    card-l: 16px # 侧边栏、文章横幅位置的圆角
    card: 12px # 文章内大部分卡片的圆角
    image: revert # 技术类文章插图圆角
  leftbar:
    background-opacity: 0.3
